### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by hf02** [hf02/scroll-for-worldedit#11]
again, title

**Comment by Rozbiynk** [comment]
still wait...

**Comment by hf02** [comment]
> still wait...

yeah. i know this mod still exists, i just haven't been playing minecraft as much lately. the most you can do is wait or submit a pull request for 1.20.1.

**Comment by Rozbiynk** [comment]
look like i cant compile it at all
![изображение](https://github.com/hf02/scroll-for-worldedit/assets/95433246/483fab72-c015-4052-af75-94e3a864bdad)

**Comment by hf02** [comment]
> look like i cant compile it at all ![изображение](https://user-images.githubusercontent.com/95433246/255531987-483fab72-c015-4052-af75-94e3a864bdad.png)

this was just a silly issue with casing, and i believe it should be fixed now as it builds successfully on my machine. since you're on windows which is case-insensitive, i think you have to re-clone or just rename:

- the folder `.../github/hf02/scrollForWorldedit` to `.../github/hf02/scrollForWorldEdit`
- the file `scrollForWorldedit.java` to `scrollForWorldEdit.java`

**Comment by hf02** [comment]
fixed in #15
