### ISSUE TITLE
Crashes when pressing Use Selected Mode key on Minecraft 1.19.2

### ISSUE THREAD

**Issue by xpopy** [hf02/scroll-for-worldedit#2]
My game crashes when i press the Use Selected Mode key, which is bound to Alt.
Installed mods:
* cloth-config-8.2.88
* Fabric-api-0.68.0
* modmenu 4.0.6
* scroll-for-worldedit-1.1.0
* worldedit-mod-7.2.12

Crash message: https://pastebin.com/rNB7DwGh

**Comment by hf02** [comment]
Thanks for making an issue!

Going to be honest, I haven't touched Minecraft in a while. I don't even have it installed right now.

Might come back to this later though to add support for >1.19, but no promises.

**Comment by hf02** [comment]
support for 1.19.3 (which came a few days after this issue) was added in #4 (v1.1.1). 1.19.2 still crashes.

i'm going to mark this issue as not planned, as i would rather just stick with latest.
