### ISSUE TITLE
A better README

### ISSUE THREAD

**Issue by hf02** [hf02/scroll-for-worldedit#7]
In #6, @TheAlan404 included a more detailed README. I rejected that one specific commit as I wanted to think about it a little more while getting 1.19.4 support now, but [someone on YouTube](https://www.youtube.com/watch?v=nZorUKIhUSQ&lc=UgzwlKOxCQIBa0SZ5Ft4AaABAg) made me realize I've missed one little keybind:

To active the mod, you press <kbd>alt</kbd>.

So yeah, a better README (hopefully also including how to activate the mod) would be good. I'll probably do it myself.

**Comment by hf02** [comment]
Updated it across everywhere to match.

Unrelated note: I hate CurseForge.

**Comment by TheAlan404** [comment]
> I hate CurseForge

who doesnt lol, thanks!
